document:
  name: Principles of the INGV Data Policy
  description: |
    Principles of the Data Policy of the Istituto Nazionale di Geofisica e Vulcanologia.
  tags:
    - INGV
    - data policy
    - database
    - dataset
    - scientific research
    - metadata
    - FAIR
